Client/Models/ErrorViewModel.cs
using System;

namespace Client.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Client/Models/Result.cs
using Communication;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Models
{
    public class Result
    {
        public List<TagModel> AllTags { get; set; }
        public string Message { get; set; }
    }
}

Client/Controllers/HomeController.cs
using Client.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Fabric;
using System.Threading;

namespace Client.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewBag.flagvalue = RequestController.flag;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Client/Controllers/RequestController.cs
using Client.Models;
using Communication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.ServiceFabric.Services.Client;
using Microsoft.ServiceFabric.Services.Remoting.Client;
using System;
using System.Collections.Generic;
using System.Fabric;
using System.Fabric.Query;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace Client.Controllers
{
    [Produces("application/json")]
    [Route("api/VideoClassifier")]
    public class RequestController : Controller
    {
        private readonly HttpClient httpClient;
        private readonly StatelessServiceContext context;
        private readonly FabricClient fabricClient;

        public static bool flag = false;

        public RequestController(HttpClient httpClient, StatelessServiceContext context, FabricClient fabricClient)
        {
            this.httpClient = httpClient;
            this.context = context;
            this.fabricClient = fabricClient;
        }

        [HttpPost]
        public async Task<IActionResult> ProcessRequest(string uploadedfileName)
        {
            flag = true;
            ViewBag.flagvalue = flag;
            string prefix = @"D:\testSet\";
            if (!string.IsNullOrEmpty(uploadedfileName))
            {
                try
                {
                    string path = Path.Combine(prefix, uploadedfileName);
                    var serviceUri = new Uri("fabric:/VideoClassifier/Orchestrator");
                    ServicePartitionList partitions = await this.fabricClient.QueryManager.GetPartitionListAsync(serviceUri);

                    if (partitions == null || partitions.Count == 0)
                    {
                        return new ContentResult { StatusCode = 404, Content = "There's no available replica. Please check service status." };
                    }
                    int partitionId = uploadedfileName.Length % 2;
                    ServicePartitionKey key = new ServicePartitionKey(partitionId);

                    var statefullProxy = ServiceProxy.Create<IOrchestrator>(serviceUri, key);

                    var testResult = await statefullProxy.GetVideoTags(path);
                    var result = new Result();
                    result.AllTags = testResult;
                    return View("~/Views/Home/Index.cshtml", result);
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    return View("~/Views/Home/Index.cshtml");
                }
            }
            else
            {
                ViewBag.Message = "You have not specified a file.";
                return View("~/Views/Home/Index.cshtml");
            }
            
        }
    }
}

Client/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Result

@section scripts {
<script type="text/javascript">
    $("#myform").submit(function(e) {
        $("#myLoadingElement").show();
    });
</script>
}

<body>

    <h2>Video classifier</h2>
    <p>Select a video and get suitable tags for the video. :)</p>
    <p></p>

    <header>
      <h2>Choose a video</h2>
    </header>

    <p>
        @Html.ValidationSummary(false)
        @using (Html.BeginForm("ProcessRequest", "Request", FormMethod.Post, new { @id = "myform"}))
        {

            <div class="form-group">
               
                <div class="col-md-10">
                    <input class="form-control" type="file" id="encryptfilefield" name="uploadedfileName" enctype='multipart/form-data'/>
                </div>
            </div>

            <br>

            <button type="submit" id="encryptfilebutton" class="btn btn-danger">Upload video</button>

        }
      @ViewBag.Message
    </p>
  
    <article>
    <p>
    @if(@Model != null && @Model.AllTags.Count > 0)
    {
            <h1>Result</h1>
        <table class="table table-bordered table-sm">
        <thead class="thead-light">
            <tr>
                <th>Tag</th>
                <th>Confidence</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var b in  @Model.AllTags)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => @b.Tag)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => @b.Confidence)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    }

    </p>
    </article>

    <footer>
      <p>
        <img src="@Url.Content("~/Content/loading_1.gif")" alt="image1" id="myLoadingElement" style="display: none;"/>
     </p>
    </footer>

</body>

Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="VideoClassifierApp" xmlns:ng="https://angularjs.org">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - jotodoro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap_solar.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                Discover video content!
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            On boarding application
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Client/Views/Shared/_ResultLayout.cshtml
<!DOCTYPE html>
<html ng-app="VideoClassifierApp" xmlns:ng="https://angularjs.org">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Client</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; JOVANA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>